### ISSUE TITLE
Define dependencies per distro

### ISSUE THREAD

**Issue by JamieCressey** [bernd/fpm-cookery#106]
I'm currently building packages as both .deb and .rpm variants. As Debian and RHEL based distros can't seem to agree on package/library naming standards, I believe the only option is to resort to two recipes per package, one for each package manager.

Is there currently a way, or would it be possible to define distro specific dependencies in a single recipe?

E.g.
```
deb-depends: 'lsb-release'
rpm-depends: 'redhat-lsb'
```

Thanks in advanced!

**Comment by bernd** [comment]
You can use this:

```ruby
  platforms [:debian, :ubuntu] do
    depends  'lsb-release'
  end

  platforms [:redhat, :centos] do
    depends 'redhat-lsb'
  end
```

Hope that helps! :smiley:

**Comment by JamieCressey** [comment]
Perfect, thanks!
