### ISSUE TITLE
Exporting cflags

### ISSUE THREAD

**Issue by archey** [bernd/fpm-cookery#110]
Is it possible or do you have an example of how to export cflags in the build method to use the hardening wrapper in debian? I have tried to export CFLAGS but fpm-cookery seems to have issues with that.

If you can be of any assistance or point me in the right direction I'd be greatful.

Thanks

**Comment by bernd** [comment]
Please try `ENV['CFLAGS'] = '...'`.

**Comment by bernd** [comment]
Closing this, please re-open if you still have problems. Thank you!
