### ISSUE TITLE
Support lifecycle hook for before and after dependency installation.

### ISSUE THREAD

**Issue by brian-oconnell** [bernd/fpm-cookery#133]
Is it possible to create a hook to run before and after dependency installation?

For example:
On the instruction for setting up nodeJS on RHEL:
https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager?utm_source=[deliciuos]&utm_medium=twitter#enterprise-linux-and-fedora
I need to run a command to make the repo available and then install a dependency.  I can work around this by putting both instruction in the build part of the package.. but it would be nice to have a pre dependency hook in which I setup the repo, and then I can just list the package as a normal dependency.

**Comment by bernd** [comment]
This is done and available 0.31.0.
```
$ fpm-cook -D
===> Starting package creation for redis-server-2.4.2 (ubuntu, deb)
===> 
DEBUG: Run lifecycle hook: before_dependency_installation (args: [])
DEBUG: Run lifecycle hook: after_dependency_installation (args: [])
DEBUG: Run lifecycle hook: before_source_download (args: [])
===> Fetching source: 
===> Using cached file /home/bernd/projects/github/fpm-cookery/recipes/redis/cache/redis-2.4.2.tar.gz
DEBUG: Run lifecycle hook: after_source_download (args: [])
```
