### ISSUE TITLE
OracleLinux support

### ISSUE THREAD

**Issue by eperdeme** [bernd/fpm-cookery#148]
Hello,

Looking at the code it uses facter to identify the OS to run and produce either RPM or DEB based files.

We recently moved to OracleLinux which broke the packaging for us as facter returns the following below.

-sh-4.1$ facter operatingsystem
OracleLinux

Would it be possible to use 'osfamily' instead of the operatingsystem fact? This should return RedHat and work for more RHEL based distros.

      def self.target
        @target ||= case platform
                    when :centos, :redhat, :fedora, :amazon, :scientific then :rpm
                    when :debian, :ubuntu                                then :deb
                    when :darwin                                         then :osxpkg
                    end

**Comment by eperdeme** [comment]
This may be a separate issue but we do an "fpm-cook clean" before the build. The clean fails the build as it can not detect the platform - even if we specify the platform on the clean with ' -p ubuntu -t deb'. We have always specified the platform on the build command, so maybe it is worth fixing fpm-cook clean to not be platform specific ?

fpm-cook clean -p ubuntu -t deb
fpm-cook --no-deps -p ubuntu -t deb

**Comment by bernd** [comment]
Thanks for the report. I added `:oraclelinux` to target to make it work for you.

Using `osfamily` for the target selection seems to have other issues like not detecting AmazonLinux properly.
