### ISSUE TITLE
create source packages

### ISSUE THREAD

**Issue by 2tata** [bernd/fpm-cookery#149]
Hi,
Really great tool ;)
How is it possible to create source packages?

**Comment by nkts** [comment]
Technically, when "-bb" will become "-ba" here https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/rpm.rb#L421

**Comment by beddari** [comment]
@mlafeldt  solved this a while back for Jimdo by creating another abstraction layer on top of fpm-cookery (layers on layers, yes I know) that I quite like https://github.com/Jimdo/buildtasks - this allows you to define a Rakefile per package/project that does calls to the correct build tool.

I've been wanting to contribute to that work but time is always the problem :)

**Comment by bernd** [comment]
Sorry, no plans for supporting source packages right now. Once FPM gets support for that to make it work on multiple target platforms, we can consider supporting it as well.
