### ISSUE TITLE
Possibility to define pre/post-(un)install scripts

### ISSUE THREAD

**Issue by brejoc** [bernd/fpm-cookery#152]
Is there a possibility to define pre/post-(un)install scripts? With fpm itself this is possible, but I haven't found an option in fpm-cookery.

**Comment by beddari** [comment]
Yes, fpm will pick up the files if you put them in buliddir. This is an (abandoned) project that has some example code for how it works https://github.com/andytinycat/puppet-omnibus/blob/master/puppet.rb#L47-L50

Look at the methods at the end for how the files are written.

**Comment by brejoc** [comment]
So there only needs to be a file named `post-install` (or `pre-uninstall`, `post-uninstall`, `pre-install`) in the build-dir?

**Comment by beddari** [comment]
Yep, that should basically be all that is needed.

**Comment by bernd** [comment]
This already works. See the [haproxy recipe](https://github.com/bernd/fpm-recipes/blob/master/haproxy/recipe.rb#L27-L30) for an example.
