### ISSUE TITLE
Retrieve attributes from `recipe.rb`

### ISSUE THREAD

**Issue by josegonzalez** [bernd/fpm-cookery#160]
It would be great to be able to expose an attribute(s) from a recipe.rb file so that it can be used in a build toolchain. For instance, one might have a system that:

- bumps the version
- runs `fpm-cook package`
- runs `lintian` on the built package
- pushes the built packages to one or more apt repositories

Currently such a thing would require either grep on the `recipe.rb` file - blech - or knowing what the attributes are, which doesn't lend itself well to generic build processes.

Instead, it would be great to have something like the following:

```
fpm-cook inspect --format '{{ .name }}_{{ .version }}_{{ .architecture }}.deb'
```

Which would spit out a "formatted" version of a recipe's attributes. FWIW, the `inspect` call templating is inspired by the one from docker, which are more or less like golang templates.

**Comment by bernd** [comment]
Should be fixed by #165
