### ISSUE TITLE
Packages with local sources

### ISSUE THREAD

**Issue by caquino** [bernd/fpm-cookery#164]
Hi,

Is it possible to package only local files? I've tried to not specify a source on the recipe but it didnt'work.

I want to package a group of scripts that are only available locally.

If it possible to point source for a local directory ?

**Comment by BaxterStockman** [comment]
@caquino -- have you tried the [`directory`](https://github.com/bernd/fpm-cookery/blob/b7798aeea09131972af03bb5bf2dd93059d039d5/lib/fpm/cookery/source_handler/directory.rb) or [`local_path`](https://github.com/bernd/fpm-cookery/blob/b7798aeea09131972af03bb5bf2dd93059d039d5/lib/fpm/cookery/source_handler/local_path.rb) source types?:

```ruby
class MyRecipe < FPM::Cookery::Recipe
  source "/path/to/my/directory/with/source/files", :with => :directory
  # <snip> rest of recipe definition
end
```

**Comment by cosmopetrich** [comment]
Just in case anyone else come across this: it appears that fpm-cook will currently throw an 'unknown file type' error if you don't use a full path to your source file. See #147 for a full example.

With a full path, the directory handler appears to work as expected.

**Comment by bernd** [comment]
@caquino @cosmopetrich It is possible to use the `:directory` method as described by @BaxterStockman  or use a file URI.

Example:

```ruby
class YourRecipe < FPM::Cookery::Recipe
  source 'file:///path/to/your/source'
end
```

I will add a check to the `:directory` source handler to throw an error if the path is not absolute.
