### ISSUE TITLE
Feature Request: "vendor-separator" attribute

### ISSUE THREAD

**Issue by sygibson** [bernd/fpm-cookery#169]
We currently have a very large collection of compiled/built DEB packages, but have chosen the tilde (~) separator over the plus (+) as the separator between the package name and vendor attributes. 

I would like to ask that a new feature attribute of "vendor-separator" (or similar) be added to allow all legal values for separator. 

I believe that these include: 

  tilde (~)
  plus (+)
  dot (.) 

Document:  Debian Policy Manual
Website:  https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Source 
Reference:  "debian_revision"

**Comment by bernd** [comment]
@sygibson There will be a `--vendor-delimiter` flag in the next fpm-cookery version!
