### ISSUE TITLE
Invalid `extracted_source` in `after_source_extraction`

### ISSUE THREAD

**Issue by elionne** [bernd/fpm-cookery#170]
When I try to use `after_source_extraction` hook the `extracted_source` argument is wrong. A double concatenation seems appear. The path look like that:

`/home/user/dev/packager.git/project1/tmp-build/home/user/dev/packager.git/project1/tmp-build/project1-branch-develop`

I use a source flag as (for testing only):

```ruby
  source "file:///home/user/dev/project1",
         :with => "git",
         :as => "project1",
         :branch => "develop"
```

**Comment by bernd** [comment]
Thank you for the report! This will be fixed in the next fpm-cookery release.
