### ISSUE TITLE
Different depends for different platforms

### ISSUE THREAD

**Issue by slavaaaaaaaaaa** [bernd/fpm-cookery#206]
Is there a specify platform-specific `depends` packages in `recipe.rb` for different platforms? I'd like to build some packages for both Ubuntu and CentOS, but obviously package naming schemes are different for some things.

Something along the lines of an `or` would be useful:

```
depends 'libsomething-devel' or 'libsomething20-devel'
```

...but I'm unaware how stupid such a proposition is in Ruby land.

**Comment by smaslennikov** [comment]
Ah, found a good example of this here: https://github.com/bernd/fpm-recipes/blob/master/haproxy/recipe.rb#L15 . Thanks!
