### ISSUE TITLE
Please release 0.34.0

### ISSUE THREAD

**Issue by madwort** [bernd/fpm-cookery#207]
Hi there,
Our project relies on the fix in #200 which was merged back in June 2018 but there has been no new release since, please could you cut a new release?
Thanks!

**Comment by bernd** [comment]
@madwort I will release 0.34.0 once #209 got merged. Thanks for the reminder! :smile:

**Comment by bernd** [comment]
@madwort I just released version 0.34.0 to rubygems.org. Have fun! :smile:

**Comment by madwort** [comment]
Thanks!
