### ISSUE TITLE
Linuxbrew

### ISSUE THREAD

**Issue by timmow** [bernd/fpm-cookery#36]
There is an [experimental fork of homebrew to linux](https://github.com/Homebrew/linuxbrew) - which has the benefit of potentially including all the homebrew formulas, and may be integrated upstream at some point as it tries hard to keep compatible with the osx homebrew as much as possible.

How difficult would it be to integrate this rather than brew2deb?

**Comment by bernd** [comment]
I am closing this because linuxbrew and fpm-cookery have different goals as far as I can see. fpm-cookery creates OS packages, linuxbrew is creating a separate package manager.

Please re-open if I got this wrong.
