### ISSUE TITLE
Integrate into fpm?

### ISSUE THREAD

**Issue by jordansissel** [bernd/fpm-cookery#8]
My massive refactor of FPM is almost done. I was thinking:

    fpm -s recipe -t rpm zeromq

Will use a cookery recipe to produce an rpm of zeromq. Thoughts?

**Comment by bernd** [comment]
Closing this because it's not going to happen I guess. :smile:

**Comment by wbraswell** [comment]
@bernd & @jordansissel 
What is the bare minimum that needs to happen, from both the fpm side & the fpm-cookery side, in order for us to finally move forward with the "real SRPM" (not "fake SRPM") solution described in the discussion linked below?
https://github.com/jordansissel/fpm/issues/237#issuecomment-415941828
