### ISSUE TITLE
Picking up all files in a directory

### ISSUE THREAD

**Issue by haf** [bernd/fpm-cookery#81]
Hi,

I'm trying to get it to pick up ALL files in the tmp-build folder. How do I do that?

`(opt/'eventstore').install Dir['*']` only picks up a single subfolder:

```
===> Using cached file /opt/teamcity-agent/work/d29baefbba8cb0b/eventstore/cache/eventstore-mono-2.0.1.tgz
===> Building in /opt/teamcity-agent/work/d29baefbba8cb0b/eventstore/tmp-build/singlenode-web
===> Installing into /opt/teamcity-agent/work/d29baefbba8cb0b/eventstore/tmp-dest
```

https://github.com/haf/fpm-recipes/blob/master/eventstore/recipe.rb

**Comment by bernd** [comment]
For most software projects you get one folder in a tarball/zip and that's why fpm-cookery changes into that directory by default.

If you want to get all directories in `tmp-build` into the package you can do the following.

```ruby
Dir.chdir(builddir) do
  (opt/'eventstore').install Dir['*']
end
```

Closing this, please re-open if you still have problems. Thank you!
