### ISSUE TITLE
Map package dependencies but no install them on build

### ISSUE THREAD

**Issue by salizzar** [bernd/fpm-cookery#99]
Hi all,

While trying to build artifacts I've discovered that fpm-cookery requires installation of packages informed on `FPM::Cookery::Recipe.depends`. This behavior is useful, of course; but I need to only map dependencies in my package metadata (RPM in this case), without install them.

I've tried to pass some information directly by `FPM::Cookery::Recipe.fpm_attributes` but after some research on code it not satisfies.

How I handle it? If allowed, it can be a feature to be developed.

Thank you.

**Comment by bernd** [comment]
You can use `fpm-cook package --no-deps` to skip the dependency installation. :smile:

**Comment by salizzar** [comment]
Hi @bernd, I forgot it... sorry, hehehe.
